export interface Concept {
  id: string;
  title: string;
  explanation: string;
  example: string;
  topic: string;
  companyCallout: string;
}

export const CONCEPTS: Concept[] = [
  {
    id: "thermo-1", title: "Otto, Diesel, Rankine Basics", explanation: "Otto and Diesel govern IC engines, while Rankine governs steam cycles. Interviews test why diesel is more efficient at higher compression ratio and where Rankine dominates.", example: "GE and Siemens turbine roles often ask where Rankine losses happen in condenser and boiler loops.", topic: "Thermodynamics", companyCallout: "Siemens, GE, HAL"
  },
  { id: "thermo-2", title: "Intercooling in Compressors", explanation: "Intercooling reduces air temperature between compression stages, so specific volume drops and compressor work required goes down.", example: "Multi-stage compressor systems in plants use intercoolers to cut power bills and improve reliability.", topic: "Thermodynamics", companyCallout: "Siemens, GE, L&T" },
  { id: "thermo-3", title: "Second Law Intuition", explanation: "Not all heat can be converted into useful work. Real devices lose available work due to irreversibility, friction, and finite temperature differences.", example: "Even perfect turbine blades cannot beat Carnot limits set by inlet and sink temperatures.", topic: "Thermodynamics", companyCallout: "ISRO, HAL, GE" },
  { id: "thermo-4", title: "Altitude Effect on Compressors", explanation: "At higher altitude, air density falls. To get same mass flow, compressor must do more volume handling, raising stage load and reducing net performance.", example: "Aerospace interviews ask why compressor maps shift and surge margins shrink at altitude.", topic: "Thermodynamics", companyCallout: "HAL, Boeing, ISRO" },
  { id: "thermo-5", title: "COP vs Efficiency", explanation: "Heat pumps and refrigerators use COP, not thermal efficiency. COP can be above 1 because it moves heat rather than creating it.", example: "EV thermal systems increasingly use heat pumps to preserve battery range in winter.", topic: "Thermodynamics", companyCallout: "Tata, Mahindra, Honeywell" },
  { id: "thermo-6", title: "Entropy Generation", explanation: "Entropy generation points to where the system is wasting potential work. Lowering pressure drop and improving heat transfer approach can improve cycle performance.", example: "Plant optimization teams track entropy rise across turbines and heat exchangers.", topic: "Thermodynamics", companyCallout: "Siemens Energy, GE" },

  { id: "fluid-1", title: "Bernoulli in Interviews", explanation: "Bernoulli links pressure, velocity and elevation along a streamline in ideal flow. Candidates are often asked where and why it fails in real systems.", example: "Venturi meters use pressure drop to estimate flowrate in pipelines and process loops.", topic: "Fluid Mechanics", companyCallout: "Schlumberger, ONGC, L&T" },
  { id: "fluid-2", title: "Cavitation Failure Mechanism", explanation: "When local pressure drops below vapor pressure, bubbles form then collapse violently on metal surfaces, causing pitting and noise.", example: "Pump impellers in oilfield systems show cavitation damage if NPSH available is too low.", topic: "Fluid Mechanics", companyCallout: "Schlumberger, ONGC, L&T" },
  { id: "fluid-3", title: "Reynolds Number Meaning", explanation: "Reynolds number compares inertial force to viscous force. It predicts whether flow tends toward laminar or turbulent behavior.", example: "Drilling mud transport and pipeline pressure loss calculations rely on flow regime assumptions.", topic: "Fluid Mechanics", companyCallout: "Halliburton, Schlumberger" },
  { id: "fluid-4", title: "Newtonian vs Non-Newtonian", explanation: "Newtonian fluids keep viscosity nearly constant with shear. Non-Newtonian fluids change apparent viscosity as shear varies.", example: "Lubricants and drilling fluids may show non-Newtonian behavior at different shear rates.", topic: "Fluid Mechanics", companyCallout: "ONGC, Schlumberger" },
  { id: "fluid-5", title: "Pascal Law in Hardware", explanation: "Pressure applied to a confined fluid transmits equally in all directions. This is the core of hydraulic amplification.", example: "Hydraulic presses and braking systems scale force with piston area ratios.", topic: "Fluid Mechanics", companyCallout: "L&T, Tata Motors" },
  { id: "fluid-6", title: "Boundary Layer Control", explanation: "Boundary layer growth drives drag and heat transfer behavior. Surface roughness and geometry strongly change separation trends.", example: "Turbomachinery blade profiles are tuned to delay separation and maintain lift.", topic: "Fluid Mechanics", companyCallout: "GE Aviation, HAL" },

  { id: "mat-1", title: "Hardness vs Toughness", explanation: "Hardness is resistance to indentation; toughness is energy absorbed before fracture. Hard materials are not always tough.", example: "Cutting tools need high hardness, while impact parts need higher toughness.", topic: "Materials Science", companyCallout: "Bosch, Tata, HAL" },
  { id: "mat-2", title: "Casting vs Forging", explanation: "Forging generally improves grain flow and fatigue strength. Casting allows complex shapes but can include porosity if process control is weak.", example: "Crankshafts are commonly forged while complex housings are cast.", topic: "Materials Science", companyCallout: "Bosch, Tata Motors" },
  { id: "mat-3", title: "Ductile vs Brittle Failure", explanation: "Ductile materials deform before fracture and give warning. Brittle materials fail suddenly with little plastic deformation.", example: "Ceramics perform well in compression but fail abruptly in tensile shock.", topic: "Materials Science", companyCallout: "HAL, ISRO" },
  { id: "mat-4", title: "Annealing vs Quenching", explanation: "Annealing relieves internal stress and softens the structure. Quenching rapidly cools to increase hardness but can increase brittleness.", example: "Heat treatment route selection depends on required strength, wear and machinability.", topic: "Materials Science", companyCallout: "Bosch, Siemens" },
  { id: "mat-5", title: "Endurance Limit", explanation: "Endurance limit is stress amplitude below which fatigue failure may not occur for very high cycle counts in many ferrous alloys.", example: "Shaft and rotating component design uses fatigue criteria more than static yield alone.", topic: "Materials Science", companyCallout: "Tata, Bosch" },
  { id: "mat-6", title: "Stress-Strain Curve Comparison", explanation: "Steel usually shows clear yield behavior; aluminium has smoother transition; ceramics remain mostly linear then fracture.", example: "Interviewers expect intuitive explanation of why ceramic parts fail without warning.", topic: "Materials Science", companyCallout: "HAL, Bosch" },

  { id: "mfg-1", title: "Draft Allowance", explanation: "Draft angle helps remove the pattern from mold without tearing cavity walls. Missing draft increases defects and rework.", example: "Foundry interviews often ask what happens if a vertical wall has zero draft.", topic: "Manufacturing & Processes", companyCallout: "Tata, L&T, Bosch" },
  { id: "mfg-2", title: "Chip Formation Types", explanation: "Continuous chips form with ductile material, high cutting speed, and sharp tools. Built-up edge appears with poor lubrication and low speeds.", example: "Machining quality and surface finish depend heavily on chip behavior.", topic: "Manufacturing & Processes", companyCallout: "Bosch, Siemens" },
  { id: "mfg-3", title: "Fixture vs Jig", explanation: "Fixture holds and locates workpiece; jig does that plus guides the tool. Correct selection improves repeatability and cycle time.", example: "Mass production lines rely on fixtures to maintain dimensional consistency.", topic: "Manufacturing & Processes", companyCallout: "Bosch, L&T" },
  { id: "mfg-4", title: "Gantt Chart Use", explanation: "Gantt charts visualize activity sequence and schedule overlap in manufacturing planning. They help identify bottlenecks early.", example: "Shop-floor planners use Gantt tracking to coordinate machining, assembly and inspection slots.", topic: "Manufacturing & Processes", companyCallout: "L&T, Siemens" },
  { id: "mfg-5", title: "Milling Tool Mounting", explanation: "Arbor and spindle interfaces ensure rigid tool mounting, minimizing chatter and runout. Setup quality directly affects tolerance.", example: "Poor clamping shows up as chatter marks and dimensional drift on milled faces.", topic: "Manufacturing & Processes", companyCallout: "Tata, Bosch" },
  { id: "mfg-6", title: "3D Printing for Prototyping", explanation: "Additive methods slash lead time for test parts and fixture prototypes. It enables faster design iteration before hard tooling.", example: "Industrial teams print jigs overnight to validate ergonomics and assembly sequence.", topic: "Manufacturing & Processes", companyCallout: "Siemens, Bosch, startups" },

  { id: "auto-1", title: "Four-Stroke Sequence", explanation: "Intake, compression, power and exhaust complete one cycle. Interviewers often ask valve states and piston motion in each stroke.", example: "This is a frequent elimination question in automobile campus rounds.", topic: "Automobile Systems", companyCallout: "Hero, Tata, Bajaj" },
  { id: "auto-2", title: "Differential Intuition", explanation: "During turns, outer wheel must rotate faster than inner wheel. Differential allows speed split while still transmitting torque.", example: "Without differential, tire scrub and drivetrain stress rise sharply in corners.", topic: "Automobile Systems", companyCallout: "Hero, Tata, Mahindra" },
  { id: "auto-3", title: "Turbo vs Supercharger", explanation: "Turbo uses exhaust energy with lag risk; supercharger uses crank power with quicker response. Tradeoff is efficiency vs responsiveness.", example: "Campus interviews ask where each system is preferred for performance and drivability.", topic: "Automobile Systems", companyCallout: "Tata, Bajaj" },
  { id: "auto-4", title: "Disc vs Drum Brakes", explanation: "Discs dissipate heat better and resist fade, so performance applications prefer them. Drums are cost-effective for lower-duty use.", example: "Repeated hard braking reveals fade in drums much earlier than ventilated discs.", topic: "Automobile Systems", companyCallout: "Hero, Tata" },
  { id: "auto-5", title: "Clutch Purpose", explanation: "Clutch allows smooth engagement and temporary disconnection between engine and transmission during gear shifts.", example: "Poor clutch control causes jerks and higher drivetrain wear.", topic: "Automobile Systems", companyCallout: "Mahindra, Bajaj" },
  { id: "auto-6", title: "Wheel Hub Weight", explanation: "Reducing unsprung mass improves ride and grip because suspension can follow road inputs faster.", example: "Light hubs and control arms are common in performance-oriented trims.", topic: "Automobile Systems", companyCallout: "Hero, Bajaj, Tata" },

  { id: "ev-1", title: "BMS Responsibilities", explanation: "BMS monitors cell voltages, currents and temperatures, estimates SOC/SOH, and enforces safety cutoffs.", example: "Pack balancing and thermal alarms are core BMS interview themes.", topic: "EVs & Electrification", companyCallout: "Tata, Mahindra, ABB" },
  { id: "ev-2", title: "Regenerative Braking", explanation: "Motor acts as generator during deceleration, sending recovered energy back to battery. This improves real-world range.", example: "One-pedal driving in EVs is a direct result of regen strategy.", topic: "EVs & Electrification", companyCallout: "Tata, Hero EV, Mahindra" },
  { id: "ev-3", title: "Inverter Function", explanation: "Inverter converts DC battery power to controlled AC waveforms for traction motor torque and speed control.", example: "Motor noise and smoothness at low speed often relate to inverter switching strategy.", topic: "EVs & Electrification", companyCallout: "Siemens, ABB, Tata" },
  { id: "ev-4", title: "Li-ion vs LFP", explanation: "NMC/NCA chemistries offer higher energy density; LFP offers stronger thermal stability and cycle life at lower cost.", example: "Fleet vehicles often choose LFP for durability and safety over peak range.", topic: "EVs & Electrification", companyCallout: "Mahindra, Tata" },
  { id: "ev-5", title: "V2G Basics", explanation: "Vehicle-to-grid allows bidirectional power flow where EV battery can support grid during peak demand windows.", example: "Campus questions often test charger architecture required for V2G compliance.", topic: "EVs & Electrification", companyCallout: "Siemens, ABB, Schneider" },
  { id: "ev-6", title: "Battery Thermal Management", explanation: "Battery packs need tight thermal control for safety, charging speed and life. Liquid cooling is common in high-performance packs.", example: "Fast charging is limited when pack temperature exits target band.", topic: "EVs & Electrification", companyCallout: "Tata, Mahindra" },

  { id: "des-1", title: "Factor of Safety", explanation: "Factor of safety bridges uncertainty in loads, material variability and service conditions. Critical systems need conservative margins.", example: "Lifting equipment design uses higher FoS than static machine frames.", topic: "Design & Mechanisms", companyCallout: "L&T, Siemens" },
  { id: "des-2", title: "Everyday Linkages", explanation: "Four-bar, slider-crank and cam-follower mechanisms convert motion in compact ways with predictable kinematics.", example: "Wiper systems and engine valve trains are common mechanism interview examples.", topic: "Design & Mechanisms", companyCallout: "Any core mechanical role" },
  { id: "des-3", title: "Stress Concentration", explanation: "Sharp corners and holes magnify local stress and accelerate crack initiation. Fillets and smooth transitions reduce risk.", example: "Bracket redesign with larger fillet radius can drastically improve fatigue life.", topic: "Design & Mechanisms", companyCallout: "Bosch, L&T" },
  { id: "des-4", title: "Bearing Selection Logic", explanation: "Load type, speed, environment and lubrication decide bearing type and arrangement. Misfit leads to heat and premature failure.", example: "Interviews often ask radial vs thrust load cases and bearing choice.", topic: "Design & Mechanisms", companyCallout: "Tata, Bosch" },
  { id: "des-5", title: "Kinematic Pairs", explanation: "Lower pairs (revolute, prismatic) and higher pairs define relative motion constraints in machine design.", example: "Robot joints, piston-cylinder and cam interfaces are standard examples.", topic: "Design & Mechanisms", companyCallout: "Siemens, L&T" },
  { id: "des-6", title: "Failure Modes Thinking", explanation: "Good design discusses yielding, buckling, fatigue, wear and thermal failure instead of only static stress checks.", example: "Interviewers value candidates who mention both design load and misuse load scenarios.", topic: "Design & Mechanisms", companyCallout: "HAL, L&T" },

  { id: "ia-1", title: "PLC vs Microcontroller", explanation: "PLCs are rugged industrial controllers with deterministic scan cycles and rich I/O integration. Microcontrollers are flexible but not plant-hardened by default.", example: "Factory automation prefers PLCs due to reliability, maintenance support and safety ecosystem.", topic: "Industrial Automation", companyCallout: "Siemens, ABB, Honeywell" },
  { id: "ia-2", title: "Ladder Logic Basics", explanation: "Ladder diagrams represent relay-style control logic in a visual, maintainable format for technicians and engineers.", example: "Motor start-stop interlock logic is a classic ladder interview problem.", topic: "Industrial Automation", companyCallout: "Siemens, ABB" },
  { id: "ia-3", title: "Sensors and Actuators Loop", explanation: "Automation loops read sensor signals, execute control logic, then command actuators to hold setpoints and sequence operations.", example: "Conveyor sorting systems combine photoelectric sensors with pneumatic actuators.", topic: "Industrial Automation", companyCallout: "Honeywell, Emerson" },
  { id: "ia-4", title: "PID in Plants", explanation: "PID control balances response speed and stability by combining proportional, integral and derivative action.", example: "Temperature loops in process plants often run PI or PID with anti-windup handling.", topic: "Industrial Automation", companyCallout: "Honeywell, Emerson" },
  { id: "ia-5", title: "SCADA Purpose", explanation: "SCADA enables supervisory monitoring, alarms, trends and remote operation over distributed industrial assets.", example: "Pipeline and utility networks rely on SCADA for centralized visibility.", topic: "Industrial Automation", companyCallout: "L&T, Schneider" },
  { id: "ia-6", title: "Interlocks and Safety", explanation: "Interlocks prevent unsafe sequences by requiring preconditions before equipment can start or continue running.", example: "Pump start permissive may require valve open, tank level valid and no trip present.", topic: "Industrial Automation", companyCallout: "ABB, Siemens, Honeywell" },

  { id: "gdt-1", title: "Why GD&T Exists", explanation: "GD&T defines functional geometry in a language manufacturing and inspection both understand. It controls variation better than simple plus-minus dimensions.", example: "Two parts can be within size tolerance yet fail assembly without geometric control.", topic: "GD&T & Engineering Drawing", companyCallout: "Bosch, Siemens, L&T" },
  { id: "gdt-2", title: "First vs Third Angle", explanation: "Projection method determines where top and side views are placed relative to front view. Mixing standards creates manufacturing mistakes.", example: "Global supplier chains must check drawing projection symbol before machining.", topic: "GD&T & Engineering Drawing", companyCallout: "Siemens, ABB" },
  { id: "gdt-3", title: "Datums in Practice", explanation: "Datums establish reference frames for measurement and mating conditions. They are chosen based on functional interfaces.", example: "Housing bores are often controlled relative to mounting face and centerline datums.", topic: "GD&T & Engineering Drawing", companyCallout: "Bosch, L&T" },
  { id: "gdt-4", title: "Position Tolerance", explanation: "Position controls location of features within a tolerance zone relative to datums, especially for hole patterns and pins.", example: "Bolt hole patterns with true position reduce assembly mismatch in production.", topic: "GD&T & Engineering Drawing", companyCallout: "Siemens, Bosch" },
  { id: "gdt-5", title: "Straightness Flatness Parallelism", explanation: "Form and orientation tolerances control geometry independent of or relative to datums based on requirement.", example: "Guide rails need flatness and parallelism to avoid carriage binding.", topic: "GD&T & Engineering Drawing", companyCallout: "ABB, L&T" },
  { id: "gdt-6", title: "Drawing Title Block Reading", explanation: "Title block carries material, scale, revision, finish and general tolerances. Missing this context causes process errors.", example: "Revision mismatch between shop floor and QA leads to rejected batches.", topic: "GD&T & Engineering Drawing", companyCallout: "Bosch, Siemens" },
];
